version: '3.8'

services:
  db:
    image: postgis/postgis:latest
    container_name: postgres_with_postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: incidents_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network
    platform: linux/amd64
  web:
    build: .
    container_name: django_app
    command: ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/incidents_db
    networks:
      - app_network

volumes:
  pgdata:

networks:
  app_network:
    driver: bridge
